version: "3.6"
services:
  app:
    image: nginx:stable-alpine
    volumes:
      - ./app:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    networks:
      - example
  puppeteer-cucumber:
    image: enrise/puppeteer-cucumber:2.1
    volumes:
      - ./test/features:/home/node/app/features
      - ./test/results:/home/node/app/test
      - ./entrypoint.sh:/home/node/app/entrypoint.sh
      - ./node_modules:/home/node/app/node_modules
    user: ${USERID}:${GROUPID}
    networks:
      - example
    environment:
      - HOST=app

networks:
  example:
