version: "3.6"
services:
  app:
    image: nginx:stable-alpine
    volumes:
      - ./app:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    networks:
      example:
        aliases:
          - todo-app.com
  puppeteer-cucumber:
    image: puppeteer-cucumber
    volumes:
      - ./test/features:/home/node/app/features
      - ./test/results:/home/node/app/test
      - ./test/node_modules:/home/node/app/node_modules
    user: ${USERID}:${GROUPID}
    networks:
      - example

networks:
  example:
